{{- if and .Values.backend.persistence.enabled (not .Values.backend.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mmmail.backendName" . }}-drive
  labels:
    {{- include "mmmail.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    {{- toYaml .Values.backend.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size | quote }}
  {{- if .Values.backend.persistence.storageClassName }}
  storageClassName: {{ .Values.backend.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
