apiVersion: v1
kind: Service
metadata:
  name: {{ include "mmmail.frontendName" . }}
  labels:
    {{- include "mmmail.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-admin
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    {{- include "mmmail.frontendSelectorLabels" . | nindent 4 }}
