import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const OPENAPI_DTS = resolve(__dirname, '../../src/service/api/__generated__/openapi.d.ts');

describe('generated openapi.d.ts contract', () => {
  const text = readFileSync(OPENAPI_DTS, 'utf8');

  it('starts with the auto-generation banner', () => {
    expect(text.startsWith('/**\n * This file was auto-generated by openapi-typescript.')).toBe(true);
  });

  it('exports the canonical paths/components/operations interfaces', () => {
    expect(text).toMatch(/export interface paths\b/);
    expect(text).toMatch(/export interface components\b/);
    expect(text).toMatch(/export type \$defs\b|export interface operations\b/);
  });

  it('declares the v2 routes that the auth and workspace surfaces rely on', () => {
    expect(text).toMatch(/['"]\/api\/v2\/auth\/login['"]/);
    expect(text).toMatch(/['"]\/api\/v2\/platform\/contracts['"]/);
  });
});
