/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";


export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: () => import("@/layouts/base-layout/index.vue"),
  blank: () => import("@/layouts/blank-layout/index.vue"),
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  admin: () => import("@/views/admin/index.vue"),
  "business-overview": () => import("@/views/business-overview/index.vue"),
  calendar: () => import("@/views/calendar/index.vue"),
  collaboration: () => import("@/views/collaboration/index.vue"),
  "command-center": () => import("@/views/command-center/index.vue"),
  community: () => import("@/views/community/index.vue"),
  contacts: () => import("@/views/contacts/index.vue"),
  docs: () => import("@/views/docs/index.vue"),
  drive: () => import("@/views/drive/index.vue"),
  home: () => import("@/views/home/index.vue"),
  integrations_simplelogin: () => import("@/views/integrations/simplelogin/index.vue"),
  mail: () => import("@/views/mail/index.vue"),
  meet: () => import("@/views/meet/index.vue"),
  notes: () => import("@/views/notes/index.vue"),
  notifications: () => import("@/views/notifications/index.vue"),
  pass: () => import("@/views/pass/index.vue"),
  search: () => import("@/views/search/index.vue"),
  security_authenticator: () => import("@/views/security/authenticator/index.vue"),
  settings: () => import("@/views/settings/index.vue"),
  share: () => import("@/views/share/index.vue"),
  sheets: () => import("@/views/sheets/index.vue"),
  vpn: () => import("@/views/vpn/index.vue"),
  wallet: () => import("@/views/wallet/index.vue"),
};
