/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admin',
    path: '/admin',
    component: 'layout.base$view.admin',
    meta: {
      title: 'admin',
      i18nKey: 'route.admin',
      icon: 'mdi:shield-account-outline',
      order: 11,
      orgRequired: true,
      roles: ['admin'],
      requires: ['admin.read']
    }
  },
  {
    name: 'business-overview',
    path: '/business-overview',
    component: 'layout.base$view.business-overview',
    meta: {
      title: 'business-overview',
      i18nKey: 'route.business-overview',
      icon: 'icon-park-outline:building-three',
      order: 2,
      orgRequired: true,
      requires: ['BUSINESS'],
      fallback: 'upgrade'
    }
  },
  {
    name: 'calendar',
    path: '/calendar',
    component: 'layout.base$view.calendar',
    meta: {
      title: 'calendar',
      i18nKey: 'route.calendar',
      icon: 'mdi:calendar-month-outline',
      order: 3,
      orgRequired: true,
      requires: ['calendar.read']
    }
  },
  {
    name: 'collaboration',
    path: '/collaboration',
    component: 'layout.base$view.collaboration',
    meta: {
      title: 'collaboration',
      i18nKey: 'route.collaboration',
      icon: 'mdi:account-group-outline',
      order: 8,
      orgRequired: true,
      requires: ['collaboration.read']
    }
  },
  {
    name: 'command-center',
    path: '/command-center',
    component: 'layout.base$view.command-center',
    meta: {
      title: 'command-center',
      i18nKey: 'route.command-center',
      icon: 'mdi:view-dashboard-outline',
      order: 9,
      orgRequired: true,
      requires: ['command-center.read']
    }
  },
  {
    name: 'community',
    path: '/community',
    component: 'layout.base$view.community',
    meta: {
      title: 'community',
      i18nKey: 'route.community',
      icon: 'mdi:forum-outline',
      order: 13,
      orgRequired: true,
      requires: ['community.read']
    }
  },
  {
    name: 'contacts',
    path: '/contacts',
    component: 'layout.base$view.contacts',
    meta: {
      title: 'contacts',
      i18nKey: 'route.contacts',
      icon: 'mdi:contacts-outline',
      order: 14,
      orgRequired: true,
      requires: ['contacts.read']
    }
  },
  {
    name: 'docs',
    path: '/docs',
    component: 'layout.base$view.docs',
    meta: {
      title: 'docs',
      i18nKey: 'route.docs',
      icon: 'mdi:file-document-outline',
      order: 5,
      orgRequired: true,
      requires: ['docs.read']
    }
  },
  {
    name: 'drive',
    path: '/drive',
    component: 'layout.base$view.drive',
    meta: {
      title: 'drive',
      i18nKey: 'route.drive',
      icon: 'mdi:folder-outline',
      order: 4,
      orgRequired: true,
      requires: ['drive.read']
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'integrations',
    path: '/integrations',
    component: 'layout.base',
    meta: {
      title: 'integrations',
      i18nKey: 'route.integrations'
    },
    children: [
      {
        name: 'integrations_simplelogin',
        path: '/integrations/simplelogin',
        component: 'view.integrations_simplelogin',
        meta: {
          title: 'integrations_simplelogin',
          i18nKey: 'route.integrations_simplelogin'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'mail',
    path: '/mail',
    component: 'layout.base$view.mail',
    meta: {
      title: 'mail',
      i18nKey: 'route.mail',
      icon: 'mdi:email-outline',
      order: 2,
      orgRequired: true,
      requires: ['mail.read']
    }
  },
  {
    name: 'meet',
    path: '/meet',
    component: 'layout.base$view.meet',
    meta: {
      title: 'meet',
      i18nKey: 'route.meet',
      icon: 'mdi:video-outline',
      order: 17,
      orgRequired: true,
      requires: ['meet.read']
    }
  },
  {
    name: 'notes',
    path: '/notes',
    component: 'layout.base$view.notes',
    meta: {
      title: 'notes',
      i18nKey: 'route.notes',
      icon: 'mdi:notebook-outline',
      order: 19,
      featureFlag: 'feat.notes.enabled'
    }
  },
  {
    name: 'notifications',
    path: '/notifications',
    component: 'layout.base$view.notifications',
    meta: {
      title: 'notifications',
      i18nKey: 'route.notifications',
      icon: 'mdi:bell-outline',
      order: 10,
      orgRequired: true,
      requires: ['notifications.read']
    }
  },
  {
    name: 'pass',
    path: '/pass',
    component: 'layout.base$view.pass',
    meta: {
      title: 'pass',
      i18nKey: 'route.pass',
      icon: 'mdi:key-outline',
      order: 7,
      orgRequired: true,
      requires: ['pass.read']
    }
  },
  {
    name: 'search',
    path: '/search',
    component: 'layout.base$view.search',
    meta: {
      title: 'search',
      i18nKey: 'route.search'
    }
  },
  {
    name: 'security',
    path: '/security',
    component: 'layout.base',
    meta: {
      title: 'security',
      i18nKey: 'route.security'
    },
    children: [
      {
        name: 'security_authenticator',
        path: '/security/authenticator',
        component: 'view.security_authenticator',
        meta: {
          title: 'security_authenticator',
          i18nKey: 'route.security_authenticator'
        }
      }
    ]
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      title: 'settings',
      i18nKey: 'route.settings',
      icon: 'mdi:cog-outline',
      order: 12,
      orgRequired: true,
      requires: ['settings.read']
    }
  },
  {
    name: 'share',
    path: '/share',
    component: 'layout.base$view.share',
    meta: {
      title: 'share',
      i18nKey: 'route.share'
    }
  },
  {
    name: 'sheets',
    path: '/sheets',
    component: 'layout.base$view.sheets',
    meta: {
      title: 'sheets',
      i18nKey: 'route.sheets',
      icon: 'mdi:table',
      order: 6,
      orgRequired: true,
      requires: ['sheets.read']
    }
  },
  {
    name: 'vpn',
    path: '/vpn',
    component: 'layout.base$view.vpn',
    meta: {
      title: 'vpn',
      i18nKey: 'route.vpn',
      icon: 'mdi:vpn',
      order: 16,
      orgRequired: true,
      requires: ['vpn.read']
    }
  },
  {
    name: 'wallet',
    path: '/wallet',
    component: 'layout.base$view.wallet',
    meta: {
      title: 'wallet',
      i18nKey: 'route.wallet',
      icon: 'mdi:wallet-outline',
      order: 15,
      orgRequired: true,
      requires: ['wallet.read']
    }
  }
];
